language: go

go:
  - "1.12"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_script:

jobs:
  include:
    - stage: Lint
      script:
        - make lint
    - stage: Build
      script: make clean all
      if: branch = master AND type IN (pull_request)
    - stage: Unit test
      script:
        - make test
      if: branch = master AND type IN (pull_request)
    - stage: Release
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io/amis
        - make docker
        - make docker.push
      if: tag =~ ^v
      env: REV="$TRAVIS_TAG"
